/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.Component;
import java.awt.ComponentOrientation;
import java.awt.Image;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JList;
import javax.swing.ListCellRenderer;
import org.json.JSONObject;
import twitter4j.Status;
import twitter4j.Twitter;

/**
 *
 * @author David Botello
 */
public class Panel_Tweet extends javax.swing.JPanel implements ListCellRenderer{

    /**
     * Creates new form Panel_Tweet
     */
    public Panel_Tweet() {
        initComponents();
    }

  
    public void setTweets(String texto)
    {
      this.Texto.setText(texto);
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Imagen = new javax.swing.JLabel();
        Nombre = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Texto = new javax.swing.JTextPane();

        setBackground(new java.awt.Color(204, 241, 255));

        Imagen.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N

        Nombre.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N

        Texto.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jScrollPane2.setViewportView(Texto);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(Imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 975, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 976, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 40, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(jScrollPane2)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Imagen;
    private javax.swing.JLabel Nombre;
    private javax.swing.JTextPane Texto;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

    @Override
    /**
     * Metodo que se encarga de renderizar los datos extraidos de twitter en diferentes paneles, para que los mensajes 
     * quedes separados uno de otros.
     */
    public Component getListCellRendererComponent(JList list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
       
       JSONObject dato = (JSONObject) value;
       JSONObject informacionUsuario;
        try 
        {
        informacionUsuario  = (JSONObject)dato.get("user");
        Nombre.setText(informacionUsuario.get("name") + "  @"+informacionUsuario.get("screen_name") +" "+dato.get("created_at"));
            System.out.println(dato.get("text").toString());
        Texto.setText(dato.get("text").toString());
//        ImageIcon imagen = new ImageIcon(new URL(informacionUsuario.get("profile_image_url_https").toString()));
//        Image image = imagen.getImage(); // transform it 
//        Image newimg = image.getScaledInstance(120, 120,  java.awt.Image.SCALE_SMOOTH); // scale it the smooth way  
//        imagen = new ImageIcon(newimg);  
//        this.Imagen.setIcon(imagen);
        }
        catch (Exception ex) 
        {
            
        }
        return this;
    }
}
