/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.TwitControlador;
import Controlador.twitterConexion;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

/**
 *
 * @author David Botello
 */
public class Ventana_Principal extends javax.swing.JFrame implements Runnable {
private TwitControlador twitControlador;
private DefaultListModel StatusNow = new DefaultListModel();
private Thread hilo;

private boolean ciclo = true; 
    /**
     * Creates new form Ventana_Principal
     */
    public Ventana_Principal() {
        initComponents();
        
        this.twitControlador = new TwitControlador();
        this.setLocation(950, 250);
        this.setVisible(true);
        cargarTweet();
     //   hilo = new Thread(this);
       // hilo.start();
     //   refrescar();
       
        
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Texto = new javax.swing.JTextField();
        Twit = new javax.swing.JButton();
        Panel = new javax.swing.JScrollPane();
        Lista = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 204, 255));

        Texto.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N

        Twit.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        Twit.setText("TWEET");
        Twit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TwitActionPerformed(evt);
            }
        });

        Lista.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        Lista.setModel(StatusNow);
        Lista.setCellRenderer(new Panel_Tweet());
        Panel.setViewportView(Lista);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PROGRAMA DE PRUEBA TWITTER");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jButton1.setText("REFRESCAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(Panel)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(Texto, javax.swing.GroupLayout.PREFERRED_SIZE, 993, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(42, 42, 42)
                            .addComponent(Twit, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 895, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(138, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Texto)
                    .addComponent(Twit, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE))
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
 * Evento que permite postear un nuevo Tweet 
 * @param evt 
 */
    private void TwitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TwitActionPerformed
        // TODO add your handling code here:
      this.twitControlador.updateTwit(this.Texto.getText());
      cargarTweet();
      this.Texto.setText("");
      
    }//GEN-LAST:event_TwitActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        cargarTweet();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * Metodo para cargar en una lista los tweets extraido de la cuanta de Twitter
     */
    public void cargarTweet()
    {
  
       JSONArray informacion = this.twitControlador.showTwit();
       
       try 
       {      
         for (int i = 0; i < informacion.length(); i++)
         {
         
           this.StatusNow.addElement(informacion.getJSONObject(i));
         }
       }
       catch (Exception ex) 
       {
            
       }
      informacion = null;
    }
 
    private void refrescar()
    {
      while (this.ciclo) 
        {
            try
            {
                
                Thread.sleep(30000);
                System.out.println("refrescar.....");
                cargarTweet();
                
                          
                if(!this.ciclo)
                    this.ciclo = false;
                
            } 
            catch (Exception ex) 
            {
     
            }
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> Lista;
    private javax.swing.JScrollPane Panel;
    private javax.swing.JTextField Texto;
    private javax.swing.JButton Twit;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        refrescar();
    }
}
